dist: xenial

language: minimal

script:
  - tools/build-ping360-bootloader.sh || travis_terminate 1

before_deploy:
  - git tag continuous-deployment -f
  - git remote set-url origin https://${GITHUB_TOKEN}@github.com/bluerobotics/ping360-bootloader
  - git push origin continuous-deployment -f

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: build/ping360-bootloader
  overwrite: true
  skip_cleanup: true
  on:
    branch: master
